---
driver:
  name: vagrant
  network:
      - ["private_network", {ip: "10.11.11.101"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: debian-7.6

suites:
  - name: lamp
    data_bags_path: "test/integration/default/data_bags"
    run_list:
      - recipe[lamp::default]
    attributes: {
      authorization: { sudo: { users: ["vagrant"]}}
    }
